### PR TITLE
add state and handler to form

### PR DESCRIPTION
**Pull request by JafariM**

### CODE REVIEW

**Comment by XeniyaDob** [comment]
Hi Masooma,

Excellent, your app is working as expected!  

I received your pull request from this link https://github.com/JafariM/react-todo/pull/3/files, and I see files in this PR are from the last PR, #2 https://github.com/JafariM/react-todo/pull/2/files

I reviewed your code from here https://github.com/JafariM/react-todo/commit/a6d811646ab562122303ac7676c04592e37d657e

And here
https://github.com/JafariM/react-todo/commit/9de2d563ff60e1c5ebf375ef9e8a6a3f5bccb20e

Please, in your next homework, send the last changes as a pull request, so I can approve them for merging.

Anyway, great job! 
You knocked out the lesson requirements.
Just an extra tip: try to split your commits into smaller pieces. That way, it's easier to keep track of what changes you made and when. The subheadings provide a good guideline for what code you should chunk into the same commit. And you can use the subheading as your commit message since it describes exactly what you did.
Let me know if this makes sense or if you need more explanation.

**Comment by JafariM** [comment]
Thank you for your review. Sorry I did push some extra changes after I submit the assignment, because I just noticed a better way to get the value from text input. 
Can you explain more about subheading? 
Thank you.

**Comment by XeniyaDob** [comment]
Sure, no worries. This is optional. If you don't like it, you don't need to do it. This tip is only for convenience in tracking your changes.
For example, on homework 1-3, you can do 3 commits with corresponding names instead of one commit.
Screen Shot 2023-04-05 at 9 11 11 AM

**Comment by JafariM** [comment]
Ok, I get it now. Thank you for clarification.

**Pull request merged**
